// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC4Is0igLkqqm3Ylw3AWYZGmyMRXnwhSw',
    appId: '1:122877635084:web:8a064722715f00b7badc29',
    messagingSenderId: '122877635084',
    projectId: 'fir-auth-b662c',
    authDomain: 'fir-auth-b662c.firebaseapp.com',
    databaseURL: 'https://fir-auth-b662c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-b662c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8RjuEPcgpqLLKI1kzUugIDAz_g1aJvU',
    appId: '1:122877635084:android:e2a5d78881345bebbadc29',
    messagingSenderId: '122877635084',
    projectId: 'fir-auth-b662c',
    databaseURL: 'https://fir-auth-b662c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-b662c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEM0DlUJchxImkzaYNRv54eXKF0nw__YA',
    appId: '1:122877635084:ios:336f0d563ed9f634badc29',
    messagingSenderId: '122877635084',
    projectId: 'fir-auth-b662c',
    databaseURL: 'https://fir-auth-b662c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-b662c.appspot.com',
    androidClientId: '122877635084-0u9l3a76f84sv7uchfcl7qpocrc89478.apps.googleusercontent.com',
    iosClientId: '122877635084-kp6j1be9lla70odlf9ld8dsqduahpph6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePunbiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEM0DlUJchxImkzaYNRv54eXKF0nw__YA',
    appId: '1:122877635084:ios:336f0d563ed9f634badc29',
    messagingSenderId: '122877635084',
    projectId: 'fir-auth-b662c',
    databaseURL: 'https://fir-auth-b662c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-b662c.appspot.com',
    androidClientId: '122877635084-0u9l3a76f84sv7uchfcl7qpocrc89478.apps.googleusercontent.com',
    iosClientId: '122877635084-kp6j1be9lla70odlf9ld8dsqduahpph6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePunbiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC4Is0igLkqqm3Ylw3AWYZGmyMRXnwhSw',
    appId: '1:122877635084:web:602c0b8de6e6ced1badc29',
    messagingSenderId: '122877635084',
    projectId: 'fir-auth-b662c',
    authDomain: 'fir-auth-b662c.firebaseapp.com',
    databaseURL: 'https://fir-auth-b662c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-b662c.appspot.com',
  );
}
